export const RouteIndex = '/'
export const Routepage = '/page'
export const RoutePlumbing = '/page/plumbing'
export const RouteElect = '/page/electrician'
export const RouteCleaning = '/page/cleaning'
export const RouteCarpentry = '/page/carpentry'